driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: true
    use_vagrant_berkshelf_plugin: true
    customize:
      memory: 1024
      cpus: 1

provisioner:
  name: chef_solo
  require_chef_omnibus: '11.10.4'
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: centos-6.5

